apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: server
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wernerravil/bun-hono-hello:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
